language: php

php:
  - "5.6"
  - "7.2"
  - "7.3"

before_script:
  - composer self-update
  - composer require codeclimate/php-test-reporter:dev-master --dev
  - composer install

script:
  - export SYMFONY_PHPUNIT_VERSION=5.7
  - php vendor/bin/simple-phpunit

after_script:
  - php vendor/bin/php-coveralls -v

